# Generated by Django 3.0.5 on 2020-04-12 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='username',
        ),
        migrations.AddField(
            model_name='files',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Abhi',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
