# Generated by Django 3.0.5 on 2020-04-12 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200412_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='fileSize',
            field=models.CharField(default=200, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
